-- CREATE TABLE todos (
--     id         SERIAL NOT NULL,
--     title        VARCHAR(255)     NOT NULL,
--     body        VARCHAR(255)      NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     PRIMARY KEY(id)
-- );
